export enum HeaderTabRoutes {
    ONDEMAND_LAVKA = 'catalog/ondemand-lavka',
    SPLIT = 'catalog/split',
    FASHION_DEP = 'catalog/fashion-dep',
    TOVARY_DLIA_DOMA = 'catalog/tovary-dlia-doma',
    KIDS_DEP = 'catalog/kids-dep',
    TOVARY_DLIA_KRASOTY = 'catalog/tovary-dlia-krasoty',
    ELECTRONICS_DEP = 'catalog/electronics-dep',
    FLOWERS_DEP = 'catalog/flowers-dep',
    TOVARY_KAK_U_IKEA = 'catalog/tovary-kak-u-ikea',
    PRODUKTY_NAPITKI = 'catalog/produkty-napitki',
    TECHNIC_DEP = 'catalog/technic-dep',
    MEBEL = 'catalog/mebel',
    TOVARY_DLIA_ZDOROVIA = 'catalog/tovary-dlia-zdorovia',
    ALICA_CASHBACK = 'catalog/alica-cashback',
    BYTOVAIA_TEKHNIKA = 'catalog/bytovaia-tekhnika',
    DACHA_SAD_I_OGOROD = 'catalog/dacha-sad-i-ogorod',
    TSVETY_BUKETY_KOMPOZITSII = 'catalog/tsvety-bukety-kompozitsii',
    TOVARY_DLIA_ZHIVOTNYKH = 'catalog/tovary-dlia-zhivotnykh',
    TOVARY_DLIA_AVTO_I_MOTOTEKHNIKI = 'catalog/tovary-dlia-avto-i-mototekhniki',
    HOBBY_DEP = 'catalog/hobby-dep',
    BOOKS_DEP = 'catalog/books-dep',
    SCHOOL_DEP = 'catalog/school-dep',
}

export const HeaderTabRouteTitles = new Map<HeaderTabRoutes, string>([
    [HeaderTabRoutes.ONDEMAND_LAVKA, 'По клику'],
    [HeaderTabRoutes.SPLIT, 'Сплит 0012'],
    [HeaderTabRoutes.FASHION_DEP, 'Одежда'],
    [HeaderTabRoutes.TOVARY_DLIA_DOMA, 'Дом'],
    [HeaderTabRoutes.KIDS_DEP, 'Детям'],
    [HeaderTabRoutes.TOVARY_DLIA_KRASOTY, 'Красота'],
    [HeaderTabRoutes.ELECTRONICS_DEP, 'Электроника'],
    [HeaderTabRoutes.FLOWERS_DEP, 'Цветы'],
    [HeaderTabRoutes.TOVARY_KAK_U_IKEA, 'ИКЕА'],
    [HeaderTabRoutes.PRODUKTY_NAPITKI, 'Продукты'],
    [HeaderTabRoutes.TECHNIC_DEP, 'Бытовая техника'],
    [HeaderTabRoutes.MEBEL, 'Мебель'],
    [HeaderTabRoutes.TOVARY_DLIA_ZDOROVIA, 'Аптека'],
    [HeaderTabRoutes.ALICA_CASHBACK, 'Алиса'],
    [HeaderTabRoutes.BYTOVAIA_TEKHNIKA, 'Бытовая техника'],
    [HeaderTabRoutes.DACHA_SAD_I_OGOROD, 'Дача'],
    [HeaderTabRoutes.TSVETY_BUKETY_KOMPOZITSII, 'Цветы'],
    [HeaderTabRoutes.TOVARY_DLIA_ZHIVOTNYKH, 'Зоо'],
    [HeaderTabRoutes.TOVARY_DLIA_AVTO_I_MOTOTEKHNIKI, 'Авто'],
    [HeaderTabRoutes.HOBBY_DEP, 'Хобби'],
    [HeaderTabRoutes.BOOKS_DEP, 'Книги'],
    [HeaderTabRoutes.SCHOOL_DEP, 'Школа'],
]);
