name: Storybook

on:
    push:
        branches: [master]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        environment:
            name: Storybook
            url: ${{ steps.build-publish.outputs.page_url }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: npm ci
                  build_command: npm run storybook:build
                  path: storybook-static
                  checkout: false
